name: Test workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependancies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependancies
        run: npm ci
      - name: Build for deployment
        run: npm build
      - name: Depoly
        run: echo "Deploying......."